# Generated by Django 3.2.3 on 2021-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Morning_Time', models.TimeField(null=True)),
                ('Awake_Sleep', models.IntegerField(null=True)),
                ('Quality_Sleep', models.IntegerField(null=True)),
                ('Night_Time', models.TimeField(null=True)),
                ('Productivity', models.IntegerField(null=True)),
                ('Quality_Day', models.IntegerField(null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Week_Day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], default='monday', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Data Sleep',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
