# Generated by Django 3.2.3 on 2021-05-31 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210530_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleepaction',
            options={},
        ),
        migrations.AddField(
            model_name='sleepaction',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
